# Site settings
title: Yue Zelda Zhang
description: Personal Portfolio Website
baseurl: ""
url: "https://roelno.github.io"

# Build settings
markdown: kramdown

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Photos
    url: /photos/